// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81e4e565-7bea-4f4f-816a-def22c28f42f"),
                            Description = "Category 1 Description",
                            Name = "Category Name 1"
                        },
                        new
                        {
                            Id = new Guid("15813940-b20f-48c4-af36-c3375d69339d"),
                            Description = "Category 2 Description",
                            Name = "Category Name 2"
                        });
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ff2a6b2-7f3d-4b5f-8069-821f8765a3dd"),
                            CategoryId = new Guid("15813940-b20f-48c4-af36-c3375d69339d"),
                            Description = "Product 1 Description",
                            Name = "Product 1 Name",
                            Price = 10.0
                        },
                        new
                        {
                            Id = new Guid("5dc9ba5e-53c0-4166-87de-5f6f57021256"),
                            CategoryId = new Guid("81e4e565-7bea-4f4f-816a-def22c28f42f"),
                            Description = "Product 2 Description",
                            Name = "Product 2 Name",
                            Price = 20.0
                        },
                        new
                        {
                            Id = new Guid("25e7bfec-7c34-4081-bbd7-e7c90e13bd27"),
                            CategoryId = new Guid("15813940-b20f-48c4-af36-c3375d69339d"),
                            Description = "Product 3 Description",
                            Name = "Product 3 Name",
                            Price = 30.0
                        },
                        new
                        {
                            Id = new Guid("d57b60ef-449f-4b86-bfa7-9102bf93dff6"),
                            CategoryId = new Guid("81e4e565-7bea-4f4f-816a-def22c28f42f"),
                            Description = "Product 4 Description",
                            Name = "Product 4 Name",
                            Price = 40.0
                        });
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.HasOne("Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
